/**
 * Canonical, single-source disclosure + trademark + risk copy.
 *
 * EVERY disclaimer shown anywhere in the product (footer, legal pages, OAuth
 * connect screen, order confirmation, welcome flows) MUST import from this
 * module. Never hardcode a disclaimer inline in a component — drift between
 * copies is itself a compliance risk.
 *
 * This module is intentionally dependency-free (pure strings/data, no React,
 * no fs/path/process) so it is safe to import into BOTH the client bundle and
 * the server crawler injector.
 *
 * ACCURACY RULE: every string here is either (a) verbatim from the approved
 * compliance spec, or (b) traceable to code in this repo. Do not add a claim
 * you cannot trace to one of those two sources. Unresolved facts are left as
 * clearly-labeled pending markers, never invented.
 */

/** Semver + effective date for the disclosure copy as a set. Acknowledgment
 * flows should persist which version a user was shown. */
export const DISCLOSURE_VERSION = "1.0.0";
export const DISCLOSURE_EFFECTIVE_DATE = "2026-07-25";

/**
 * Full trademark / affiliation disclaimer. Shown on /disclosures and on any
 * page or modal that names Robinhood (including the OAuth connect screen).
 */
export const TRADEMARK_ROBINHOOD =
  "Fincai is not affiliated with, endorsed by, or sponsored by Robinhood Markets, Inc. Robinhood and the Robinhood logo are trademarks of Robinhood Markets, Inc. Fincai connects to your Robinhood account through Robinhood's official Trading API, only with your explicit authorization, and only for as long as you keep that authorization active.";

/** One-line trademark disclaimer for the global footer of every route. */
export const TRADEMARK_ROBINHOOD_SHORT =
  "Not affiliated with or endorsed by Robinhood Markets, Inc.";

/** "Not investment advice" — the core positioning disclaimer. */
export const NOT_ADVICE =
  "Fincai is a software tool for market analysis and order entry. It is not an investment adviser, broker-dealer, or financial planner. Nothing Fincai produces is personalized investment advice, a recommendation to buy or sell any security, or an offer or solicitation of any kind. Fincai does not consider your financial situation, investment objectives, tax position, or risk tolerance.";

/**
 * Short-form "not a recommendation" line for the point of decision (the order
 * confirmation modal). Contextual disclosure at the moment an order is placed is
 * materially stronger than a footer. Must not be dismissible ("don't show again").
 */
export const NOT_A_RECOMMENDATION_SHORT =
  "This is order entry, not a recommendation. Fincai is not advising you to place this trade — you are placing it on your own decision.";

/** General trading + options risk. */
export const RISK_GENERAL =
  "Trading involves substantial risk, including the possible loss of the entire amount invested. Options carry additional risk and are not suitable for every investor. Before trading options, review the Options Clearing Corporation's disclosure document, Characteristics and Risks of Standardized Options.";

/** Automated / agentic strategy risk. */
export const RISK_AUTONOMOUS =
  "Automated and agentic strategies can act faster than you can review them. Software fails, market data can be delayed or wrong, and connectivity can be interrupted. Risk controls reduce but do not eliminate the possibility of loss. You remain responsible for every position in your account.";

/** AI output limitations. */
export const AI_LIMITATIONS =
  "Fincai's analysis is generated by AI systems that can be incomplete, out of date, or simply wrong, including in ways that read as confident and specific. Treat every output as a starting point for your own research, not a conclusion. Verify before you act.";

/** No performance representations. */
export const NO_PERFORMANCE =
  "Fincai does not publish, promise, project, or imply any level of trading performance. Any results shown in product demonstrations are illustrative software behavior, not trading results.";

/**
 * User responsibility. NOTE: the autonomous strategy runner, once a user arms
 * a strategy in LIVE mode, can place and close live orders within the user's
 * configured limits WITHOUT a separate per-order confirmation. The manual chat
 * / terminal path is confirmation-first. This string is therefore written to
 * be accurate for BOTH paths: the user authorizes the activity (either per
 * order, or by arming a live strategy) and remains responsible for the result.
 */
export const USER_RESPONSIBILITY =
  "You are solely responsible for the orders placed and the positions held in your account. Manual trades require your explicit confirmation before they are sent. If you arm a strategy in live mode, you authorize it to place and close orders automatically within the limits you set, without a separate confirmation for each order — you can pause or stop it at any time.";

/**
 * No fund movement — the strongest negative trust guarantee. Verified against
 * the integration model: Fincai holds only a Robinhood Trading API OAuth
 * authorization (order entry), never banking/transfer credentials, and stores
 * no Robinhood password.
 */
export const NO_FUND_MOVEMENT =
  "Fincai cannot deposit, withdraw, or transfer funds or securities out of your brokerage account. Fincai's access is limited to the permissions you grant during authorization, and you can revoke it at any time from your Robinhood account settings.";

/** Paper-trading default. */
export const PAPER_DEFAULT =
  "New accounts run in paper (simulated) mode by default. Live trading requires an explicit, separate opt-in.";

/**
 * Data sent to third-party AI model providers. This describes the flow that is
 * verifiable from the codebase (Fincai's AI chat and analysis features send
 * prompt content to a model provider). The provider's own retention/training
 * terms are NOT verifiable from this repo and are marked pending review.
 * [PENDING HD-06] confirm exact per-provider data categories + retention/training.
 */
export const DATA_TO_AI_PROVIDERS =
  "When you use Fincai's AI chat or analysis features, the content of your prompts — including any stock symbols, watchlists, or position details you reference or ask about — is sent to a third-party AI model provider to generate a response. By default this provider is Anthropic (Claude). If you connect your own OpenAI or Google Gemini API key, analysis requests are sent to that provider instead. Fincai does not control whether these providers retain or use that content to train their models; review each provider's terms. (The precise data categories per provider and their retention practices are under review and will be enumerated here.)";

/** Public link to the OCC options disclosure document referenced by RISK_GENERAL. */
export const OCC_ODD_URL =
  "https://www.theocc.com/company-information/documents-and-archives/options-disclosure-document";

/** First sentence of a longer string, for truncated footer/inline use. */
export function firstSentence(text: string): string {
  const match = text.match(/^[\s\S]*?[.!?](\s|$)/);
  return (match ? match[0] : text).trim();
}

export interface DisclosureEntry {
  id: string;
  title: string;
  version: string;
  effectiveDate: string;
  text: string;
}

/**
 * Version registry: every disclosure carries a semver + effective date so an
 * acknowledgment record can answer "what exact text did the user see when they
 * agreed". All share the module-level version/date until a string is revised
 * independently.
 */
export const DISCLOSURES: Record<string, DisclosureEntry> = {
  TRADEMARK_ROBINHOOD: {
    id: "TRADEMARK_ROBINHOOD",
    title: "Third-party trademarks",
    version: DISCLOSURE_VERSION,
    effectiveDate: DISCLOSURE_EFFECTIVE_DATE,
    text: TRADEMARK_ROBINHOOD,
  },
  NOT_ADVICE: {
    id: "NOT_ADVICE",
    title: "Not investment advice",
    version: DISCLOSURE_VERSION,
    effectiveDate: DISCLOSURE_EFFECTIVE_DATE,
    text: NOT_ADVICE,
  },
  NOT_A_RECOMMENDATION_SHORT: {
    id: "NOT_A_RECOMMENDATION_SHORT",
    title: "Not a recommendation (point of decision)",
    version: DISCLOSURE_VERSION,
    effectiveDate: DISCLOSURE_EFFECTIVE_DATE,
    text: NOT_A_RECOMMENDATION_SHORT,
  },
  RISK_GENERAL: {
    id: "RISK_GENERAL",
    title: "Trading and options risk",
    version: DISCLOSURE_VERSION,
    effectiveDate: DISCLOSURE_EFFECTIVE_DATE,
    text: RISK_GENERAL,
  },
  RISK_AUTONOMOUS: {
    id: "RISK_AUTONOMOUS",
    title: "Automated strategy risk",
    version: DISCLOSURE_VERSION,
    effectiveDate: DISCLOSURE_EFFECTIVE_DATE,
    text: RISK_AUTONOMOUS,
  },
  AI_LIMITATIONS: {
    id: "AI_LIMITATIONS",
    title: "AI limitations",
    version: DISCLOSURE_VERSION,
    effectiveDate: DISCLOSURE_EFFECTIVE_DATE,
    text: AI_LIMITATIONS,
  },
  NO_PERFORMANCE: {
    id: "NO_PERFORMANCE",
    title: "No performance representations",
    version: DISCLOSURE_VERSION,
    effectiveDate: DISCLOSURE_EFFECTIVE_DATE,
    text: NO_PERFORMANCE,
  },
  USER_RESPONSIBILITY: {
    id: "USER_RESPONSIBILITY",
    title: "Your responsibility",
    version: DISCLOSURE_VERSION,
    effectiveDate: DISCLOSURE_EFFECTIVE_DATE,
    text: USER_RESPONSIBILITY,
  },
  NO_FUND_MOVEMENT: {
    id: "NO_FUND_MOVEMENT",
    title: "Fincai cannot move money",
    version: DISCLOSURE_VERSION,
    effectiveDate: DISCLOSURE_EFFECTIVE_DATE,
    text: NO_FUND_MOVEMENT,
  },
  PAPER_DEFAULT: {
    id: "PAPER_DEFAULT",
    title: "Paper trading by default",
    version: DISCLOSURE_VERSION,
    effectiveDate: DISCLOSURE_EFFECTIVE_DATE,
    text: PAPER_DEFAULT,
  },
  DATA_TO_AI_PROVIDERS: {
    id: "DATA_TO_AI_PROVIDERS",
    title: "Where your data goes",
    version: DISCLOSURE_VERSION,
    effectiveDate: DISCLOSURE_EFFECTIVE_DATE,
    text: DATA_TO_AI_PROVIDERS,
  },
};
